@echo off
setlocal

:: Variables
set "psScript=%temp%\psScript.ps1"

:: PowerShell script to open file dialog and show form for text replacement
echo Add-Type -AssemblyName System.Windows.Forms > "%psScript%"
echo Add-Type -AssemblyName System.Drawing >> "%psScript%"
echo $openFileDialog = New-Object System.Windows.Forms.OpenFileDialog >> "%psScript%"
echo $openFileDialog.Filter = "Text files (*.txt)|*.txt|All files (*.*)|*.*" >> "%psScript%"
echo if ($openFileDialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { >> "%psScript%"
echo     $inputFile = $openFileDialog.FileName >> "%psScript%"
echo     $form = New-Object System.Windows.Forms.Form >> "%psScript%"
echo     $form.Text = 'Replace Special Characters' >> "%psScript%"
echo     $form.Size = New-Object System.Drawing.Size(600, 700) >> "%psScript%"
echo     $form.StartPosition = 'CenterScreen' >> "%psScript%"
echo     $lblSearch = New-Object System.Windows.Forms.Label >> "%psScript%"
echo     $lblSearch.Text = 'Search For (multiline):' >> "%psScript%"
echo     $lblSearch.Location = New-Object System.Drawing.Point(10, 20) >> "%psScript%"
echo     $txtSearch = New-Object System.Windows.Forms.TextBox >> "%psScript%"
echo     $txtSearch.Location = New-Object System.Drawing.Point(150, 20) >> "%psScript%"
echo     $txtSearch.Size = New-Object System.Drawing.Size(400, 100) >> "%psScript%"
echo     $txtSearch.Multiline = $true >> "%psScript%"
echo     $txtSearch.ScrollBars = 'Vertical' >> "%psScript%"
echo     $lblReplace = New-Object System.Windows.Forms.Label >> "%psScript%"
echo     $lblReplace.Text = 'Replace With (multiline):' >> "%psScript%"
echo     $lblReplace.Location = New-Object System.Drawing.Point(10, 130) >> "%psScript%"
echo     $txtReplace = New-Object System.Windows.Forms.TextBox >> "%psScript%"
echo     $txtReplace.Location = New-Object System.Drawing.Point(150, 130) >> "%psScript%"
echo     $txtReplace.Size = New-Object System.Drawing.Size(400, 100) >> "%psScript%"
echo     $txtReplace.Multiline = $true >> "%psScript%"
echo     $txtReplace.ScrollBars = 'Vertical' >> "%psScript%"
echo     $lblContent = New-Object System.Windows.Forms.Label >> "%psScript%"
echo     $lblContent.Text = 'File Content:' >> "%psScript%"
echo     $lblContent.Location = New-Object System.Drawing.Point(10, 240) >> "%psScript%"
echo     $txtContent = New-Object System.Windows.Forms.TextBox >> "%psScript%"
echo     $txtContent.Multiline = $true >> "%psScript%"
echo     $txtContent.ScrollBars = 'Both' >> "%psScript%"
echo     $txtContent.Location = New-Object System.Drawing.Point(10, 270) >> "%psScript%"
echo     $txtContent.Size = New-Object System.Drawing.Size(560, 300) >> "%psScript%"
echo     $btnReplace = New-Object System.Windows.Forms.Button >> "%psScript%"
echo     $btnReplace.Text = 'Replace All' >> "%psScript%"
echo     $btnReplace.Location = New-Object System.Drawing.Point(250, 590) >> "%psScript%"
echo     $btnReplace.Add_Click({ >> "%psScript%"
echo         $content = $txtContent.Text >> "%psScript%"
echo         $search = [regex]::Escape($txtSearch.Text) >> "%psScript%"
echo         $replace = $txtReplace.Text >> "%psScript%"
echo         $content = $content -replace $search, $replace >> "%psScript%"
echo         $txtContent.Text = $content >> "%psScript%"
echo         [System.IO.File]::WriteAllText($inputFile, $content) >> "%psScript%"
echo         [System.Windows.Forms.MessageBox]::Show('Replacements done and saved successfully!', 'Success', [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information) >> "%psScript%"
echo     }) >> "%psScript%"
echo     $form.Controls.Add($lblSearch) >> "%psScript%"
echo     $form.Controls.Add($txtSearch) >> "%psScript%"
echo     $form.Controls.Add($lblReplace) >> "%psScript%"
echo     $form.Controls.Add($txtReplace) >> "%psScript%"
echo     $form.Controls.Add($lblContent) >> "%psScript%"
echo     $form.Controls.Add($txtContent) >> "%psScript%"
echo     $form.Controls.Add($btnReplace) >> "%psScript%"
echo     $content = Get-Content -Raw -Path $inputFile >> "%psScript%"
echo     $txtContent.Text = $content >> "%psScript%"
echo     [void] $form.ShowDialog() >> "%psScript%"
echo } >> "%psScript%"

:: Execute PowerShell script
powershell -NoProfile -ExecutionPolicy Bypass -File "%psScript%"

:: Clean up
del "%psScript%"

exit /b
